language: node_js
node_js:
- '6.10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: 
  api_key:
    secure: huwHnbPcAOZls/qlYUS+6Dfp8xvTJ98L7YWDH0StZdeCw0D0NriBDlUoC68Zr98McJyy0JZXjwq8uJuo2+zvqDcRE6DjNA9yotS7vuSbdfbOWGQ3EXmS+2E2+MCHNsVxcFaz1OBMPUNHrBRPEh863bAy1R70A4RchMYw6EuHOuWEsP0HcE5owkGYDlGASc0x7C8UdgDUVV6ngPnu5K28yevdKPUwgB2JFuhhfw3LfGjEIZ3gdzuTMtIqduHxe3Ec83+9JeTQjYJhicmcH5yVDf5Pl0vbGJKuvGtEOTqHm2j6rx03O6+Nwr0hbC8L0rKnIPRZFS5QX/wbQIK8ncdcAmQJPzZYzTsCGpPf1ZY2DV/YdnGqLJXYEMxpaYCHQakRDDNjGD4dqzbTc5tT6vKVHGakmErIl2SuB7xYDSn8R/MzIfksrwQHnoaUV/f8NFHvFV+OHUg71kueQwpixC9HfBG8inOMhSEDzdpCEWIz41ZhIDOpasK0804JUtpVABDtjisIGtJs5b3SD8yzgSuHM5IzJ89wLq9cDyhY+ZNnm4OdWm4omdD5GwUX7fw+edPnbaEhuCyYxayERK73CpDOb62VcbU3LVGRl2doIPhZnBFHn3HsHxy49LeIKYDIuLXBdkvwWKgrz5r17haZTnLKBe9vbiOoj5GLzUaBmE3U3bc=
  on:
    tags: true
    repo: ladenedge/textanalytics
