language: node_js
node_js:
- '6.10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: jnmiller@cryptofreak.org
  api_key:
    secure: oW8JGWljFtG0uFwUzNYk0+JoMqo5lEg1KHZo/rC0bzQ1VwRjhFZqd1TPwIApv+aGudYiGX2UHr/PLWLpLOPgu+60OJISRgPmlIhU6mYSUn6mrNTKDQ41ZfFhGHJpzoTsso3DCk4djgWCb5x5K2Efn+D8Vm6O6MuRypV5H7KUZuahWYGeUTiA3WDOapghJv46tlKIg24XzTGeUhRxwyqA+JxyeMDJsUHgd2FJsYieOxosnkLFa6BQC9oxaEHmMaF4BJKZtSpJxQJ2MDg5sa1+obe3LBXgZcdISo4CNGqaRcSswSCVNJ/0IXg61PFl/g4OJvLR/gp3aE4RJdMXzSKBKZzm4W+HfdVBz/YCTgCWLPgVu5Nl+1flvYnSEtKoQJugee1YBzXZs6C2/YACHK1ufiy9hXhVd5Hc+pVCAW5IMyOgBKBaEKHF11V7+7HVrmWnt/7GAosnjsJDuimfwqAMlvNnGMz4GoeR50+BpYc2fS8voXhvzhKApBoZRN2sjm97qBiCj/SVMexlXSM1Yww1OU4jh45XLJDfm47wrKHMDtYDAX1ECQgoM5sEAQ7N7yoirZwdVtpwVpU0aDg/Y8g72NkAO8a9lRXEupjuBJP8GuZw1qhJ4mbKRSpx9pLtSVc5meP+LnAd+QNVV2yv2Qjdi65YGrE7cijDUSF9eyvnQKQ=
  on:
    tags: true
    repo: ladenedge/textanalytics
